Name: Itha Ram Sai Manoj

Roll No: E21007

In [1]:
#Importing the functions: 
import numpy as np
import pandas as pd
import os

In [2]:
# For test-train splitting, importing the function from sklearn library
from sklearn.model_selection import train_test_split

# For finding mean squared error, importing the function from sklearn library
from sklearn.metrics import mean_squared_error 

# Importing the KNN Regressor function from sklearn library
from sklearn.neighbors import KNeighborsRegressor

from math import sqrt

In [3]:
#Reading the file from the specified folder

os.chdir('C:\\Users\\Manoj\\IML')
cars = pd.read_csv('cars.csv')
cars

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8,307.0,130,3504,12.0,70,US
1,Buick Skylark 320,15.0,8,350.0,165,3693,11.5,70,US
2,Plymouth Satellite,18.0,8,318.0,150,3436,11.0,70,US
3,AMC Rebel SST,16.0,8,304.0,150,3433,12.0,70,US
4,Ford Torino,17.0,8,302.0,140,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4,140.0,86,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4,97.0,52,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4,135.0,84,2295,11.6,82,US
404,Ford Ranger,28.0,4,120.0,79,2625,18.6,82,US
405,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US

In [4]:
# Randomizing the data
cars = cars.sample(len(cars))

#K value in K fold
k = 5

# Size for each part
split_size = int(len(cars)/k)
split_size

81

In [5]:
# List to store the data 

cars_list = []

#Splitting of the data into k parts and putting in the above declared list
z=0
for i in range(0,k):
    
    #Splitting the data into subsets
    cars_fold = cars.iloc[z : z + split_size] 
    #Increasing the value of z
    z = z + split_size
    #Appending the above divided data into the list
    cars_list.append(cars_fold)
cars_list

[                        Car   MPG  Cylinders  Displacement  Horsepower  \
 339       Volkswagen Rabbit  29.8          4          89.0          62
 295         Dodge St. Regis  18.2          8         318.0         135
 390          Toyota Corolla  34.0          4         108.0          70
 112  Plymouth Custom Suburb  13.0          8         360.0         170
 188        Honda Civic CVCC  33.0          4          91.0          53
 ..                      ...   ...        ...           ...         ...
 83          Volvo 145e (sw)  18.0          4         121.0         112
 63         Plymouth Cricket  26.0          4          91.0          70
 329               Mazda GLC  46.6          4          86.0          65
 311      Fiat Strada Custom  37.3          4          91.0          69
 315         Pontiac Phoenix  33.5          4         151.0          90

      Weight  Acceleration  Model  Origin
 339    1845          15.3     80  Europe
 295    3830          15.2     79      US
 390    2245          16.9     82   Japan
 112    4654          13.0     73      US
 188    1795          17.5     75   Japan
 ..      ...           ...    ...     ...
 83     2933          14.5     72  Europe
 63     1955          20.5     71      US
 329    2110          17.9     80   Japan
 311    2130          14.7     79  Europe
 315    2556          13.2     79      US

 [81 rows x 9 columns],
                             Car   MPG  Cylinders  Displacement  Horsepower  \
 125                  Opel Manta  24.0          4         116.0          75
 206              Dodge Aspen SE  20.0          6         225.0         100
 141                 AMC Matador  16.0          6         258.0         110
 293             Ford LTD Landau  17.6          8         302.0         129
 401             Ford Mustang GL  27.0          4         140.0          86
 ..                          ...   ...        ...           ...         ...
 229  Oldsmobile Cutlass Supreme  17.0          8         260.0         110
 287           Pontiac Lemans V6  21.5          6         231.0         115
 9            AMC Ambassador DPL  15.0          8         390.0         190
 252                 Ford Fiesta  36.1          4          98.0          66
 127                 Volvo 144ea  19.0          4         121.0         112

      Weight  Acceleration  Model  Origin
 125    2158          15.5     73  Europe
 206    3651          17.7     76      US
 141    3632          18.0     74      US
 293    3725          13.4     79      US
 401    2790          15.6     82      US
 ..      ...           ...    ...     ...
 229    4060          19.0     77      US
 287    3245          15.4     79      US
 9      3850           8.5     70      US
 252    1800          14.4     78      US
 127    2868          15.5     73  Europe

 [81 rows x 9 columns],
                             Car   MPG  Cylinders  Displacement  Horsepower  \
 27                  Audi 100 LS  24.0          4         107.0          90
 399           Dodge Charger 2.2  36.0          4         135.0          84
 334         Audi 5000s (diesel)  36.4          5         121.0          67
 254              Datsun B210 GX  39.4          4          85.0          70
 52   AMC Hornet Sportabout (sw)  18.0          6         258.0         110
 ..                          ...   ...        ...           ...         ...
 281                   Audi 5000  20.3          5         131.0         103
 76   Oldsmobile Delta 88 Royale  12.0          8         350.0         160
 111                Ford Country  12.0          8         400.0         167
 64       Toyota Corolla Hardtop  24.0          4         113.0          95
 136                 Datsun B210  31.0          4          79.0          67

      Weight  Acceleration  Model  Origin
 27     2430          14.5     70  Europe
 399    2370          13.0     82      US
 334    2950          19.9     80  Europe
 254    2070          18.6     78   Japan
 52     2962          13.5     71      US
 ..      ...           ...    ...     ...
 281    2830          15.9     78  Europe
 76     4456          13.5     72      US
 111    4906          12.5     73      US
 64     2278          15.5     72   Japan
 136    1950          19.0     74   Japan

 [81 rows x 9 columns],
                                    Car   MPG  Cylinders  Displacement  \
 256  Oldsmobile Cutlass Salon Brougham  19.9          8         260.0
 338                          Subaru DL  33.8          4          97.0
 221                          Ford F108  13.0          8         302.0
 38                          Ford Pinto  25.0          4          98.0
 174                     Toyota Corolla  29.0          4          97.0
 ..                                 ...   ...        ...           ...
 70                    Pontiac Catalina  14.0          8         400.0
 160                     Chevrolet Nova  18.0          6         250.0
 49                   Dodge Monaco (sw)  12.0          8         383.0
 77              Chrysler Newport Royal  13.0          8         400.0
 213                         Ford Pinto  26.5          4         140.0

      Horsepower  Weight  Acceleration  Model Origin
 256         110    3365          15.5     78     US
 338          67    2145          18.0     80  Japan
 221         130    3870          15.0     76     US
 38            0    2046          19.0     71     US
 174          75    2171          16.0     75  Japan
 ..          ...     ...           ...    ...    ...
 70          175    4385          12.0     72     US
 160         105    3459          16.0     75     US
 49          180    4955          11.5     71     US
 77          190    4422          12.5     72     US
 213          72    2565          13.6     76     US

 [81 rows x 9 columns],
                                Car   MPG  Cylinders  Displacement  Horsepower  \
 113       Oldsmobile Vista Cruiser  12.0          8         350.0         180
 394          Buick Century Limited  25.0          6         181.0         110
 162                  Ford Maverick  15.0          6         250.0          72
 40                     AMC Gremlin  19.0          6         232.0         100
 298  Chevrolet Malibu Classic (sw)  19.2          8         267.0         125
 ..                             ...   ...        ...           ...         ...
 268                AMC Concord d/l  18.1          6         258.0         120
 6                 Chevrolet Impala  14.0          8         454.0         220
 344                   Honda Accord  32.4          4         107.0          72
 39     Volkswagen Super Beetle 117   0.0          4          97.0          48
 312          Buick Skylark Limited  28.4          4         151.0          90

      Weight  Acceleration  Model  Origin
 113    4499          12.5     73      US
 394    2945          16.4     82      US
 162    3158          19.5     75      US
 40     2634          13.0     71      US
 298    3605          15.0     79      US
 ..      ...           ...    ...     ...
 268    3410          15.1     78      US
 6      4354           9.0     70      US
 344    2290          17.0     80   Japan
 39     1978          20.0     71  Europe
 312    2670          16.0     79      US

 [81 rows x 9 columns]]

In [6]:
# total elements in the list should be equal to k
print(len(cars_list))

# total observations in per element of list should be equal to split_size               
for i in range(5):    
    print(len(cars_list[i]))

5
81
81
81
81
81

In [7]:
#Defining the KNN Regression function
def Knn_regression(test,train):
    
    #Seperating the target and predictor variables

    X = cars[['Displacement', 'Horsepower', 'Weight', 'Acceleration']]
    #y = iris[['species']]
    y = cars.MPG
    
    # Stratify is to divide in homogenous
    (X_Train, X_Test, y_Train, y_Test) = train_test_split(X, y, test_size = 0.3, random_state = 7)
    
    #Instantiate Learning model (k=3)
    knn = KNeighborsRegressor(n_neighbors=3) #3NN

    #Fitting the model
    knn.fit(X_Train, y_Train)
    
    #Predicting the response
    pred = knn.predict(X_Test)
    
    #Calculating the root mean square error
    error = sqrt(mean_squared_error(y_Test,pred)) 
    return(error)

In [8]:
fold = 0
rmse=[]
trained_data = [] 
for fold in range(k):
    fold_select=[]
    
    # for loop will hold 1 part of test data and other parts of combined train data
    for j in range(k):             
        if j != fold:
            
            #will hold the parts of train data
            fold_select.append(j)            
        else:
            test_data = cars_list[j]
    trained_data = pd.concat([cars_list[fold_select[0]],cars_list[fold_select[1]],cars_list[fold_select[2]],cars_list[fold_select[3]]])
        
    err = Knn_regression(test_data,trained_data)
    rmse.append(err)

print(rmse)

mean_rmse = np.mean(rmse)   
print("Mean RMSE is : ", mean_rmse)

[5.844219350593425, 5.844219350593425, 5.844219350593425, 5.844219350593425, 5.844219350593425]
Mean RMSE is :  5.844219350593425