Name = 'Itha Ram Sai Manoj'


Roll No: E21007

In [1]:
#Importing the required libraries

import os
import numpy as np
import pandas as pd

In [2]:
#Defining the euclidean function for calculating euclidean distance

def euclidian(a, b):
    d = np.sqrt(sum((a-b)**2))
    return d

## 1NN algorithm for Regression

In [5]:
#Reading the cars.csv file from the folder

data = pd.read_csv('cars.csv')
data

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8,307.0,130,3504,12.0,70,US
1,Buick Skylark 320,15.0,8,350.0,165,3693,11.5,70,US
2,Plymouth Satellite,18.0,8,318.0,150,3436,11.0,70,US
3,AMC Rebel SST,16.0,8,304.0,150,3433,12.0,70,US
4,Ford Torino,17.0,8,302.0,140,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4,140.0,86,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4,97.0,52,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4,135.0,84,2295,11.6,82,US
404,Ford Ranger,28.0,4,120.0,79,2625,18.6,82,US
405,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US

In [6]:
#Taking the data to be trained from the iris dataset with the help of iloc

#Predicted Variables
X_Train = data.iloc[:301, 3:6]

#Taking the data to be tested from the iris dataset with the help of iloc

#Predicted Variables
X_Test = data.iloc[301:406, 3:6]

In [7]:
#Taking the data to be trained from the iris dataset with the help of iloc

#Target Variable
Y_Train = data.iloc[:301, 1]

#Taking the data to be trained from the iris dataset with the help of iloc

#Target Variable
Y_Test = data.iloc[301:406, 1]

In [9]:
X_Train_data_Mean = X_Train.mean()
X_Train_data_Std = X_Train.std()

In [10]:
#Standardizing the training data with the help of the formula

# (Data - Mean)/Standard Deviation

X_Train = (X_Train - X_Train_data_Mean)/X_Train_data_Std
X_Train

     Displacement  Horsepower    Weight
0        0.818032    0.422495  0.403171
1        1.210194    1.264845  0.616785
2        0.918352    0.903838  0.326315
3        0.790672    0.903838  0.322924
4        0.772432    0.663166  0.341008
..            ...         ...       ...
296      1.210194    1.024174  1.370651
297      1.219314    0.711301  1.024800
298      0.453230    0.302159  0.517324
299      1.301394    0.903838  0.895953
300     -1.170138   -0.997468 -1.381469

[301 rows x 3 columns]

In [12]:
#Standardizing the training data with the help of the formula

# (Data - Mean)/Standard Deviation

X_Test = (X_Test - X_Train_data_Mean)/X_Train_data_Std
X_Test

     Displacement  Horsepower    Weight
301     -1.197499   -1.141871 -1.324958
302     -1.088058   -0.780864 -1.392772
303     -0.878297   -0.780864 -0.539445
304     -0.312854   -0.853065  0.432557
305      1.210194    0.302159  0.850744
..            ...         ...       ...
401     -0.705016   -0.636461 -0.403817
402     -1.097178   -1.454744 -1.149771
403     -0.750616   -0.684595 -0.963283
404     -0.887417   -0.804931 -0.590305
405     -0.896537   -0.732729 -0.482933

[105 rows x 3 columns]

In [18]:
def One_NN_Regression(X_train, x):
    
    #Taking an empty list to store the distances
    dist = []
    
    #Taking an empty list to store the predicted values
    Y_Pred = []

    for i in range(0, len(x)):
        
        for j in range(0, len(X_train)):
            
            #Calling the euclidean distance function to calculate the distances between trained and test data of predicted variables
            d = euclidian(X_train.iloc[j,:], x.iloc[i,:])
            
            #Appending the distances we get in to the dist list
            dist.append(d)
       
        #Calculating the least distance we obtained with the help of indexes
        min_distance = dist.index(min(dist))
        
        #Appending the minimum distances we obtained for individual test data in to the predicted list
        Y_Pred.append(Y_Train.iloc[min_distance,])
        
         #Making the list empty again
        dist  = []
    
    return pd.DataFrame(Y_Pred, Y_Test)

In [19]:
One_NN_Regression(X_Train, X_Test)

         0
MPG
34.1  26.0
35.7  29.0
27.4  23.0
25.4  20.8
23.0  16.5
...    ...
27.0  25.5
44.0  23.0
32.0  19.0
28.0  22.0
31.0  25.0

[105 rows x 1 columns]

## KNN Algorithm for Regression

In [20]:
def KNN_Regression(x_train, x, k):
    
    #Taking an empty list to store the distances
    dist = []
    
    #Taking an empty list to store the predicted values
    Y_Pred = []
    
    for i in range(0, len(x)):
        
        for j in range(0, len(x_train)):
            
            #Calling the euclidean distance function to calculate the distances between trained and test data of predicted variables
            d = euclidian(x_train.iloc[j,:], x.iloc[i,:])
            
            #Appending the distances we get in to the dist list
            dist.append(d)
        
        #Creating a dictionary of distances for every instance of training data to sort the distances in ascending order to get K Nearest neighbours 
        df_dist = {"Index":np.arange(0,len(x_train)), "Distance": dist }
        
        #Converting the dictionary into Data Frame
        df_dist = pd.DataFrame(df_dist)
        
        #Sorting the values by Distance
        df_dist = df_dist.sort_values(by = "Distance")
        
        #Getting the indexes of the K Nearest Neighbours
        indices = df_dist.iloc[0:k,0]
        
        #Finding the predicted value by taking mean of the MPG values
        min_distance = round(Y_Train.iloc[indices, ].mean(), 1)
        
        #Appending the minimum distances we obtained for individual test data in to the predicted list
        Y_Pred.append(min_distance)
        
        #Making the list empty again
        dist = []
    
    #Creating a dictonary so that we can easy access the test data and the predicted data
    final_result = {"Predicted": Y_Pred, "Actual": Y_Test}
    
    #
    final_result = pd.DataFrame(final_result)
    
    return final_result

In [21]:
KNN_Regression(X_Train, X_Test, 4)

     Predicted  Actual
301       30.0    34.1
302       31.1    35.7
303       23.2    27.4
304       20.8    25.4
305       16.8    23.0
..         ...     ...
401       24.4    27.0
402       19.1    44.0
403       22.8    32.0
404       23.5    28.0
405       24.6    31.0

[105 rows x 2 columns]

## 1NN for Classification

In [30]:
#Reading the IRIS file from the folder
data = pd.read_csv('IRIS.csv')

#We are jumbling the data as in the dataset, it is grouped by the species
data = data.sample(len(data))
data

     sepal_length  sepal_width  petal_length  petal_width          species
53            5.5          2.3           4.0          1.3  Iris-versicolor
149           5.9          3.0           5.1          1.8   Iris-virginica
82            5.8          2.7           3.9          1.2  Iris-versicolor
8             4.4          2.9           1.4          0.2      Iris-setosa
93            5.0          2.3           3.3          1.0  Iris-versicolor
..            ...          ...           ...          ...              ...
62            6.0          2.2           4.0          1.0  Iris-versicolor
119           6.0          2.2           5.0          1.5   Iris-virginica
28            5.2          3.4           1.4          0.2      Iris-setosa
65            6.7          3.1           4.4          1.4  Iris-versicolor
78            6.0          2.9           4.5          1.5  Iris-versicolor

[150 rows x 5 columns]

In [38]:
#Taking the data to be trained from the iris dataset with the help of iloc

#Predicted Variables
X_Train = data.iloc[:101, 0:4]

#Taking the data to be tested from the iris dataset with the help of iloc

#Predicted Variables
X_Test = data.iloc[101:, 0:4]

In [39]:
#Taking the data to be trained from the iris dataset with the help of iloc

#Target Variable
Y_Train = data.iloc[:101, 4:]

#Taking the data to be trained from the iris dataset with the help of iloc

#Target Variable
Y_Test = data.iloc[101:, 4:]

In [40]:
X_Train_Mean = X_Train.mean()
X_Train_Std = X_Train.std()

In [41]:
#Standardizing the training data with the help of the formula

# (Data - Mean)/Standard Deviation

X_Train1 = (X_Train - X_Train_Mean)/X_Train_Std
X_Train1

     sepal_length  sepal_width  petal_length  petal_width
53      -0.358895    -1.733637      0.151853     0.158450
149      0.102868    -0.099395      0.758720     0.808997
82      -0.012573    -0.799785      0.096684     0.028341
8       -1.628744    -0.332858     -1.282559    -1.272754
93      -0.936099    -1.733637     -0.234335    -0.231878
..            ...          ...           ...          ...
24      -1.166981     0.834457     -1.006710    -1.272754
61       0.102868    -0.099395      0.262193     0.418669
73       0.333750    -0.566321      0.538041     0.028341
7       -0.936099     0.834457     -1.227389    -1.272754
17      -0.820658     1.067920     -1.282559    -1.142644

[101 rows x 4 columns]

In [42]:
#Standardizing the training data with the help of the formula

# (Data - Mean)/Standard Deviation

X_Test1 = (X_Test - X_Train_Mean)/X_Train_Std
X_Test1

     sepal_length  sepal_width  petal_length  petal_width
48      -0.589777     1.534847     -1.227389    -1.272754
87       0.564631    -1.733637      0.372532     0.158450
137      0.680072     0.134068      0.979398     0.808997
79      -0.128014    -1.033248     -0.123995    -0.231878
121     -0.243454    -0.566321      0.648380     1.069216
97       0.449190    -0.332858      0.317362     0.158450
85       0.218309     0.834457      0.427702     0.548779
104      0.795513    -0.099395      1.144908     1.329435
29      -1.282422     0.367531     -1.172219    -1.272754
101     -0.012573    -0.799785      0.758720     0.939107
115      0.680072     0.367531      0.869059     1.459545
50       1.372717     0.367531      0.538041     0.288560
30      -1.166981     0.134068     -1.172219    -1.272754
4       -0.936099     1.301384     -1.282559    -1.272754
111      0.680072    -0.799785      0.869059     0.939107
148      0.449190     0.834457      0.924229     1.459545
74       0.680072    -0.332858      0.317362     0.158450
131      2.411684     1.768310      1.475926     1.069216
18      -0.128014     1.768310     -1.117050    -1.142644
109      1.603598     1.301384      1.310417     1.719764
136      0.564631     0.834457      1.034568     1.589654
138      0.218309    -0.099395      0.593211     0.808997
23      -0.820658     0.600994     -1.117050    -0.882426
126      0.449190    -0.566321      0.593211     0.808997
134      0.333750    -1.033248      1.034568     0.288560
20      -0.474336     0.834457     -1.117050    -1.272754
140      1.026394     0.134068      1.034568     1.589654
49      -0.936099     0.600994     -1.282559    -1.272754
42      -1.628744     0.367531     -1.337728    -1.272754
5       -0.474336     2.001773     -1.117050    -1.012535
139      1.257276     0.134068      0.924229     1.199326
71       0.333750    -0.566321      0.151853     0.158450
9       -1.051540     0.134068     -1.227389    -1.402863
89      -0.358895    -1.266711      0.151853     0.158450
2       -1.282422     0.367531     -1.337728    -1.272754
15      -0.128014     3.169089     -1.227389    -1.012535
130      1.834480    -0.566321      1.310417     0.939107
88      -0.243454    -0.099395      0.207023     0.158450
146      0.564631    -1.266711      0.703550     0.939107
91       0.333750    -0.099395      0.482871     0.288560
98      -0.820658    -1.266711     -0.399844    -0.101769
96      -0.128014    -0.332858      0.262193     0.158450
39      -0.820658     0.834457     -1.227389    -1.272754
54       0.795513    -0.566321      0.482871     0.418669
62       0.218309    -1.967100      0.151853    -0.231878
119      0.218309    -1.967100      0.703550     0.418669
28      -0.705218     0.834457     -1.282559    -1.272754
65       1.026394     0.134068      0.372532     0.288560
78       0.218309    -0.332858      0.427702     0.418669

In [62]:
def One_NN_Classification(x_train, x):
    
    #Taking an empty list to store the distances
    dist = []
    
    #Taking an empty list to store the predicted values
    Y_Pred = []

    for i in range(0, len(x)):
        
        for j in range(0, len(x_train)):
            
            #Calling the euclidean distance function to calculate the distances between trained and test data of predicted variables
            d = euclidian(x_train.iloc[j,:], x.iloc[i,:])
            
            #Appending the distances we get in to the dist list
            dist.append(d)
        
        #Calculating the least distance we obtained with the help of indexes
        min_distance = dist.index(min(dist))
        
        #Appending the minimum distances we obtained for individual test data in to the predicted list
        Y_Pred.append(Y_Train.iloc[min_distance,]['species'])
        
        #Making the list empty again
        dist  = []
    
    final_result = {"Predicted":Y_Pred,"Actual":Y_Test["species"]}
    final_result = pd.DataFrame(final_result)
    
    return final_result

In [63]:
One_NN_Classification(X_Train, X_Test)

           Predicted           Actual
48       Iris-setosa      Iris-setosa
87   Iris-versicolor  Iris-versicolor
137   Iris-virginica   Iris-virginica
79   Iris-versicolor  Iris-versicolor
121   Iris-virginica   Iris-virginica
97   Iris-versicolor  Iris-versicolor
85   Iris-versicolor  Iris-versicolor
104   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
101   Iris-virginica   Iris-virginica
115   Iris-virginica   Iris-virginica
50   Iris-versicolor  Iris-versicolor
30       Iris-setosa      Iris-setosa
4        Iris-setosa      Iris-setosa
111   Iris-virginica   Iris-virginica
148   Iris-virginica   Iris-virginica
74   Iris-versicolor  Iris-versicolor
131   Iris-virginica   Iris-virginica
18       Iris-setosa      Iris-setosa
109   Iris-virginica   Iris-virginica
136   Iris-virginica   Iris-virginica
138   Iris-virginica   Iris-virginica
23       Iris-setosa      Iris-setosa
126   Iris-virginica   Iris-virginica
134   Iris-virginica   Iris-virginica
20       Iris-setosa      Iris-setosa
140   Iris-virginica   Iris-virginica
49       Iris-setosa      Iris-setosa
42       Iris-setosa      Iris-setosa
5        Iris-setosa      Iris-setosa
139   Iris-virginica   Iris-virginica
71   Iris-versicolor  Iris-versicolor
9        Iris-setosa      Iris-setosa
89   Iris-versicolor  Iris-versicolor
2        Iris-setosa      Iris-setosa
15       Iris-setosa      Iris-setosa
130   Iris-virginica   Iris-virginica
88   Iris-versicolor  Iris-versicolor
146   Iris-virginica   Iris-virginica
91   Iris-versicolor  Iris-versicolor
98   Iris-versicolor  Iris-versicolor
96   Iris-versicolor  Iris-versicolor
39       Iris-setosa      Iris-setosa
54   Iris-versicolor  Iris-versicolor
62   Iris-versicolor  Iris-versicolor
119  Iris-versicolor   Iris-virginica
28       Iris-setosa      Iris-setosa
65   Iris-versicolor  Iris-versicolor
78   Iris-versicolor  Iris-versicolor

In [64]:
def KNN_Classification(x_train, x, k):
    
    #Taking an empty list to store the distances
    dist = []
    
    #Taking an empty list to store the predicted values
    Y_Pred = []
    
    for i in range(0, len(x)):
        
        for j in range(0, len(x_train)):
            
            #Calling the euclidean distance function to calculate the distances between trained and test data of predicted variables
            d = euclidian(x_train.iloc[j,:], x.iloc[i,:])
            
            #Appending the distances we get in to the dist list
            dist.append(d)
        
        #Creating a dictionary of distances for every instance of training data to sort the distances in ascending order to get K Nearest neighbours 
        df_dist = {"Index":np.arange(0,len(x_train)), "Distance": dist }
        
        #Converting the dictionary into Data Frame
        df_dist = pd.DataFrame(df_dist)
        
        #Sorting the values by Distance
        df_dist = df_dist.sort_values(by = "Distance")
        
        #Getting the indexes of the K Nearest Neighbours
        indices = df_dist.iloc[0:k,0]
        
        #Finding the predicted value by taking mean of the MPG values
        min_distance = round(Y_Train.iloc[indices, ].mode())
        
        #Appending the minimum distances we obtained for individual test data in to the predicted list
        Y_Pred.append(min_distance['species'][0])
        
        #Making the list empty again
        dist = []
    
    ActualList = list(Y_Test.species)
    #Creating a dictonary so that we can easy access the test data and the predicted data
    final_result = {"Predicted": Y_Pred, "Actual Value":ActualList}
    
    #
    final_result = pd.DataFrame(data = final_result,index=np.arange(0,len(Y_Test)))
    
    return final_result

In [65]:
KNN_Classification(X_Train, X_Test, 3)

          Predicted     Actual Value
0       Iris-setosa      Iris-setosa
1   Iris-versicolor  Iris-versicolor
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6   Iris-versicolor  Iris-versicolor
7    Iris-virginica   Iris-virginica
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10   Iris-virginica   Iris-virginica
11  Iris-versicolor  Iris-versicolor
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14   Iris-virginica   Iris-virginica
15   Iris-virginica   Iris-virginica
16  Iris-versicolor  Iris-versicolor
17   Iris-virginica   Iris-virginica
18      Iris-setosa      Iris-setosa
19   Iris-virginica   Iris-virginica
20   Iris-virginica   Iris-virginica
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
26   Iris-virginica   Iris-virginica
27      Iris-setosa      Iris-setosa
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa
30   Iris-virginica   Iris-virginica
31  Iris-versicolor  Iris-versicolor
32      Iris-setosa      Iris-setosa
33  Iris-versicolor  Iris-versicolor
34      Iris-setosa      Iris-setosa
35      Iris-setosa      Iris-setosa
36   Iris-virginica   Iris-virginica
37  Iris-versicolor  Iris-versicolor
38  Iris-versicolor   Iris-virginica
39  Iris-versicolor  Iris-versicolor
40  Iris-versicolor  Iris-versicolor
41  Iris-versicolor  Iris-versicolor
42      Iris-setosa      Iris-setosa
43  Iris-versicolor  Iris-versicolor
44  Iris-versicolor  Iris-versicolor
45  Iris-versicolor   Iris-virginica
46      Iris-setosa      Iris-setosa
47  Iris-versicolor  Iris-versicolor
48  Iris-versicolor  Iris-versicolor